# -*- coding: utf-8 -*-
"""Proyecto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-j4WqBgifuDdNo5mKKq0BIXI0GTvrat
"""

import pandas as pd

Data_Frame_Ciudad = pd.read_csv("mapa_medellin.txt", sep=";")
Data_Frame_Ciudad